name: CICDPipeline

on:
  push:
    branches: ["master"]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Build code using Maven
        run: mvn package

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: 'jainatul888'
          password: 'Imatuljain@88'

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: jainatul888/myimagefromgithub:latest
