name: CICDPipeline
on : 
 push:
  branches: ["master"]
jobs:
 cicdDocker:
	runs-on: ubuntu:latest
	steps: 
	-name :Checkout code
	 uses :actions/checkout@v4
	-name :Install Java And Maven
	 uses :actions/java@v4
	 with :
		java-version:17
		distribution:'temurin'
		cache:'maven'
	-name : Install Docker
	 uses : docker/setup-buildx-action@v3
	-name : Build code using Maven
	 run :mvn package
	-name : Login Dockerhub
	 uses : docker/login-action@v3
	 with : 
		username: 'jainatul888 '
		password: 'Imatuljain@88'
	-name:Build and Push Image
	 uses : docker /build-push-action@v6
	 with :
		context: .
		tag:jainatul888/myimage01atul
		push :true
		
